name: flipper
description: >
  A super app for africans
publish_to: "none" # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 99.99.99+99

# The packages below are just refrences for what packages being used
# so not referenced in the app! check each package for more real package used
#  in the specific package.
environment:
  sdk: ">=2.12.0 <3.0.0"
  # flutter: ">=1.17.0"

dependencies:
  objectbox: ^1.3.0
  objectbox_sync_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  stacked_generator:
  mockito:
  test:
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0
  objectbox_generator: any
  matcher: ^0.12.10
  msix: ^2.6.6
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
# msix_config:
#   display_name: yegobox/flipper
#   publisher_display_name: yegobox ltd
#   identity_name: yegobox.yegoboxflipper
#   msix_version: 1.26.0.0
#   publisher: CN=B0F98A1E-8AE8-4B2B-BD1B-F494D4F791AE
#   logo_path: .\assets\icon\icon.png
#   start_menu_icon_path: .\assets\icon\icon.png
#   tile_icon_path: .\assets\icon\icon.png
#   icons_background_color: #ffffff
#   architecture: x64
#   store: false

flutter:
  # deferred-components:
  #   - name: finance
  #     libraries:
  #       # Only one library from the loading unit is necessary.
  #       - package:flipper_finance/app.dart
  uses-material-design: true
  assets:
    - assets/fliper-logo.png
    - assets/
    - assets/images/
    - assets/icons/
    - vendor/
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
generate: true
# https://flutter.dev/docs/perf/deferred-components (getting ready with way forward.)
