name: flipper_rw
repository: https://github.com/yegobox/flipper
description: A super app for africans
# publish_to: "none" # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1-dev.3

# The packages below are just refrences for what packages being used
# so not referenced in the app! check each package for more real package used
#  in the specific package.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  objectbox: ^1.4.1-dev.0
  flutter:
    sdk: flutter
  objectbox_sync_flutter_libs: ^1.4.1-dev.0
  isar: ^2.2.0+1
  isar_flutter_libs: ^2.2.0+1
  flutter_lints: ^1.0.0
  flipper_dashboard: ^0.0.1-dev.5
  flipper_ui: ^1.0.3
  flipper_models: ^0.0.1-dev.5
  flipper_login: ^0.0.1-dev.5
  flipper_services: ^0.0.1-dev.6
  flipper_routing: ^0.0.1-dev.3
  loading: ^1.0.2
  flipper_localize: ^0.0.2
  universal_platform: ^1.0.0+1
  animations: ^2.0.0
  sentry_flutter: ^6.3.0
  firebase_auth_desktop: ^0.1.1-dev.0
  firebase_core: ^1.9.0
  firebase_core_desktop: ^0.1.1-dev.0
  flutterfire_ui: ^0.3.5+1
  get_storage: ^2.0.3
  firebase_auth: ^3.3.5
  google_fonts: ^2.1.0
  stacked: ^2.2.8
  firebase_messaging: ^11.2.3
  overlay_support: ^1.2.1
  stacked_themes: ^0.3.8+1
  flex_color_scheme: ^4.2.0
  path_provider: ^2.0.8
  firebase_messaging_platform_interface: ^3.1.6
  logger: ^1.1.0
  firebase_crashlytics: ^2.5.0
  path: ^1.8.0
  flutter_riverpod: any
  google_ui: ^2.7.0
  flipper_data_table: 1.0.0-dev.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  stacked_generator:
  mockito:
  test:
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  objectbox_generator: ^1.4.0
  matcher: ^0.12.10
  msix: ^2.8.17
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
msix_config:
  display_name: flipperApp
  publisher_display_name: yegobox ltd
  identity_name: yegobox.yegoboxflipper
  msix_version: 1.33.0.0
  publisher: CN=B0F98A1E-8AE8-4B2B-BD1B-F494D4F791AE
  logo_path: "./assets/icon/icon.png"
  start_menu_icon_path: "/assets/icon/icon.png"
  tile_icon_path: "./assets/icon/icon.png"
  icons_background_color: #ffffff
  architecture: x64
  store: true

flutter:
  # deferred-components:
  #   - name: finance
  #     libraries:
  #       # Only one library from the loading unit is necessary.
  #       - package:flipper_finance/app.dart
  uses-material-design: true
  assets:
    - assets/fliper-logo.png
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
generate: true
# https://flutter.dev/docs/perf/deferred-components (getting ready with way forward.)
