name: supabase_models
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.27
  brick_offline_first_with_supabase: ^1.1.2
  brick_sqlite: ^3.1.1+1
  brick_supabase: ^1.1.3
  sqflite: ^2.4.0
  supabase_flutter: ^2.8.0
  sqflite_common: ^2.5.4+6 
  sqflite_common_ffi: ^2.3.4+3
  path_provider: ^2.1.5
  path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  brick_sqlite_generators: ^3.2.2
  brick_offline_first_with_supabase_build: ^1.0.0
  build_runner: ^2.4.13