name: flipper_rw
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.170.4252223232084+1720979121

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sentry_flutter: ^8.1.0
  firebase_crashlytics: ^3.3.2
  flutter_local_notifications: ^14.1.1
  intl: ^0.19.0
  injectable: ^2.4.0
  get_it: ^7.6.0
  stacked: ^3.4.1+1
  meta: "^1.7.0"
  get: ^4.6.1
  timeago: ^3.4.0
  mime: ^1.0.5
  open_filex: ^4.1.1
  ant_icons: ^2.0.0-nullsafety.0
  pubnub: ^4.3.1
  feather_icons: ^1.1.0-nullsafety.0
  flex_color_scheme: ^4.2.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.0.2
  file_picker: ^8.0.5
  firebase_ui_auth: ^1.14.0
  azlistview: ^2.0.0
  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.2.1
  flutter_slidable: ^1.3.0
  flutter_text_drawable: ^1.0.0
  font_awesome_flutter: ^9.0.0
  upgrader: ^10.0.0-alpha.1
  universal_platform: ^1.0.0+1
  ionicons: ^0.1.2
  overlay_support: ^2.1.0
  flutter_settings_ui: ^3.0.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.6
  google_fonts: ^6.1.0
  
  number_display: ^3.0.0
  firebase_core: ^2.31.1
  cupertino_icons: ^1.0.2
  connectivity_plus: ^6.0.3
  #google_mobile_ads: ^5.0.0
  device_info_plus: ^10.1.0
  provider: ^6.0.1
  gap: ^2.0.0
  barcode: ">=2.2.3 <3.0.0"
  
  flutter_native_splash: ^2.3.2
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre
  # flipper_ui: ^1.0.3
  fluentui_system_icons: ^1.1.203
  easy_sidemenu:
    git:
      url: https://github.com/Jamalianpour/easy_sidemenu.git
      ref: master
  # flipper_socials: 1.0.0+1
  flipper_localize: ^1.0.0-dev
  tray_manager: ^0.2.3
  pinput: ^4.0.0
  flutter_screen_lock: ^9.0.4
  local_auth: ^2.1.7
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks:
  riverpod: ^2.0.0
  hooks_riverpod: ^2.0.0
  bottom_sheet: ^4.0.0
  rxdart: ^0.27.3
  swipe_to_complete: ^0.0.1
  badges: ^3.1.2
  community_charts_flutter: ^1.0.2
  fluent_ui: ^4.8.2
  dropdown_search: ^5.0.6
  loading_animation_widget: ^1.2.0+4
  email_validator_flutter: ^1.0.0
  #TODO: because this is community package, I have applied for community licence
  #  the licence is for company less than 1M in revenue and have not received 3M in outside source
  # Meaning I am using this package for now to speed up the process of development
  # if we hit that limit, we will have to switch to paid package or implement some functionality
  # by ourself. but for esence of time I do not want to wast time
  # Synfusion package compatibility https://help.syncfusion.com/flutter/system-requirements#sdk-version-compatibility
  syncfusion_flutter_datepicker: ^25.2.7
  syncfusion_flutter_datagrid: ^25.2.7
  syncfusion_flutter_xlsio: ^25.2.7
  syncfusion_flutter_datagrid_export: ^25.2.7
  syncfusion_flutter_core: ^25.2.7
  flutter_colorpicker:
    git: https://github.com/mchome/flutter_colorpicker.git
  realm: ^3.2.0
  device_type: ^0.0.6
  sizer: ^2.0.15
  # firebase_app_check: ^0.2.1+12
  talker_flutter: ^4.1.5
  collection: ^1.15.0
  # flipper_loading: ^2.0.0
  flutter_window_close: ^0.2.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  stacked_services: ^1.0.4
  url_strategy: ^0.2.0
  logger: ^1.1.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.0
  animated_icon_button: ^1.0.2
  pip_view: ^0.9.7
  getwidget: ^3.0.1
  fast_cached_network_image: ^1.1.1
  flutter_chat_ui: ^1.6.10
  firebase_remote_config: ^4.4.4
  share_plus: ^9.0.0
  firebase_messaging: ^14.9.4
  country_code_picker: ^3.0.0
  firebase_ui_localizations: ^1.9.0
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.1.11
  get_storage: ^2.1.1
  js: ^0.6.3
  flutter_web_plugins:
    sdk: flutter
  args:
  htmltopdfwidgets:
  markdown:
  string_scanner:
  pdf: ^3.10.3
  printing: ^5.11.1
  ffi: ">=2.0.0 <3.0.0"
  pdf_widget_wrapper: '>=1.0.0 <2.0.0'
  plugin_platform_interface: ^2.1.0
  web: ^0.5.1
  archive: ^3.1.0
  bidi: ^2.0.10
  crypto: ^3.0.0
  path_parsing: ">=0.2.0 <2.0.0"
  vector_math: ^2.1.0
  xml: ">=6.3.0 <7.0.0"
  dotted_line: ^3.2.2
  syncfusion_flutter_pdf: ^25.2.7
  syncfusion_flutter_barcodes: ^25.2.7
  win32: ^5.0.0
  qr: ^3.0.0
  flutter_bloc: ^8.0.1
  flutter_keyboard_visibility: ^5.4.1
  bloc: ^8.0.1
  flipper_dashboard: ^0.0.1-dev.5
  flipper_models: ^0.0.1-dev.7
  flipper_routing: ^0.0.1-dev.3
  flipper_services: ^1.0.0-dev
  flipper_login: ^0.0.1-dev.5
  # flipper_socials: 1.0.0+1
  # flipper_actionable: ^0.0.1
  amplify_api: ^2.1.0
  amplify_flutter: ^2.1.0
  amplify_auth_cognito: ^2.1.0
  amplify_storage_s3: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  msix: ^3.16.7
  patrol: ^3.6.1
  stacked_generator:
  flutter_launcher_icons: ^0.13.1
  matcher: ^0.12.10
  injectable_generator: ^2.6.0
  integration_test:
    sdk: flutter
  nock: ^1.2.3
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  build_runner: ^2.4.8
  flutter_assets_generator: ^0.0.8
  # custom_lint:
  # riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.7
  mockito: ^5.4.2
  test:
msix_config:
  display_name: flipperApp
  publish_folder_path: ./released
  app_installer: #<-- app installer configurations
    publish_folder_path: ./released
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: true
  publisher_display_name: yegobox ltd
  identity_name: yegobox.yegoboxflipper
  msix_version: 1.170.2227.0
  publisher: CN=B0F334A1E-8AET-4B2C-BD1B-F239D4F791AE
  logo_path: "./assets/icon.png"
  start_menu_icon_path: "/assets/icon.png"
  tile_icon_path: "./assets/icon.png"
  icons_background_color: #ffffff
  architecture: x64
  store: false
  enable_at_startup: true
  app_uri_handler_hosts: flipper.rw
  capabilities: internetClient
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ca/
    - google_fonts/
    - shorebird.yaml

patrol:
  app_name: Flipper
  android:
    package_name: rw.flipper
  ios:
    bundle_id: rw.flipper
  macos:
    bundle_id: rw.flipper
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    # background_color: "#1ABCFE"
    # theme_color: "#1ABCFE"
  windows:
    generate: true
    # image_path: "assets/icon/icon.png"
    # icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

generate: true

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and, run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "##FFFFFF"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/icon.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  #branding: assets/dart.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "##FFFFFF"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/icon.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    #image: assets/android12splash.png

    # Splash screen background color.
    color: "#42a5f5"

    # App icon background color.
    #icon_background_color: "#eeeeee"

    # The image_dark parameter and icon_background_color_dark set the image and icon background
    # color when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "##FFFFFF"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
# https://flutter.dev/docs/perf/deferred-components (getting ready with way forward.)
# dart run flutter_launcher_icons:main

