name: flipper_services
description: flipper models scaffold.
version: 1.0.0

# publish_to: "none"
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.4.1+1
  firebase_remote_config: ^4.2.5
  share_plus: ^7.0.2
  # in_app_review: ^2.0.6
  firebase_messaging: ^14.6.2
  image: ^4.0.17
  firebase_auth: 4.8.0
  # the bellow package has outdated image package, but I do not It is needed now
  # esc_pos_utils_plus: ^2.0.1+3
  # nfc_manager: ^3.2.0
  geolocator: ^9.0.2
  geocode: ^1.0.3
  firebase_analytics: ^10.4.2
  firebase_crashlytics: ^3.3.2
  location: 5.0.0-dev.8
  flutter_luban: ^0.1.13
  flutter_uploader: ^3.0.0-beta.4
  google_sign_in: ^6.1.3
  firebase_dynamic_links: ^5.3.2
  http: ^1.1.0
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  path: ^1.8.2
  googleapis: ^11.2.0
  timeago: ^3.4.0
  pubnub: ^4.2.4
  stacked_services: ^1.0.4
  universal_platform: ^1.0.0+1
  googleapis_auth: ^1.4.1
  uuid: ^3.0.7
  url_launcher: ^6.1.11
  flipper_nfc: ^1.2.0
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  connectivity_plus: ^4.0.1
  flutter_statusbarcolor_ns: ^0.5.0
  #TODO: real-time support on web https://github.com/pocketbase/dart-sdk/issues/11
  # TODO: find out how to take advantage this
  #   final prefs = await SharedPreferences.getInstance();

  # final store = AsyncAuthStore(
  #  save:    (String data) async => prefs.setString('pb_auth', data),
  #  initial: prefs.getString('pb_auth'),
  # );

  # final pb = PocketBase('http://example.com', authStore: store);
  # TODO: take advantage of pb.backups.upload(file) for backup of database
  pocketbase: ^0.15.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  flipper_routing: ^0.0.1-dev.3
  flipper_models: ^0.0.1-dev.7
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.1
  newrelic_mobile: ^1.0.1
  flutter_local_notifications: ^14.1.1
  local_notifier: ^0.1.5
  window_manager: ^0.3.0
  launcher_entry: ^0.1.1
  firebase_admob_config: ^1.3.1
  google_mobile_ads: ^3.1.0
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  build_runner: ^2.4.4
  test:
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - ./assets/