name: flipper_services
description: flipper models scaffold.
version: 1.0.0-dev

repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.4.2
  firebase_remote_config: ^5.1.3
  share_plus: ^9.0.0
  firebase_messaging: ^15.1.3
  image: ^4.0.17
  firebase_auth: ^5.3.3
  geolocator: ^13.0.2
  geocode: ^1.0.3
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  location: ^6.0.2
  
  google_sign_in: ^6.2.1
  
  http: ^1.2.2
  intl: ^0.19.0
  image_picker: ^0.8.7+5
  path_provider: ^2.1.4
  path: ^1.8.2
  googleapis: ^11.2.0
  timeago: ^3.4.0
  pubnub: ^4.3.1
  stacked_services: ^1.6.0
  universal_platform: ^1.0.0+1
  googleapis_auth: ^1.4.1
  flipper_nfc: ^1.2.0
  timezone: ^0.10.0
  connectivity_plus: ^6.0.5
  flutter_statusbarcolor_ns: ^0.5.0-flipper
  
  # TODO: find out how to take advantage this
  #   final prefs = await SharedPreferences.getInstance();

  # final store = AsyncAuthStore(
  #  save:    (String data) async => prefs.setString('pb_auth', data),
  #  initial: prefs.getString('pb_auth'),
  # );

  # final pb = PocketBase('http://example.com', authStore: store);
  # TODO: take advantage of pb.backups.upload(file) for backup of database
  
  get_it: ^7.7.0
  injectable: ^2.5.0
  flipper_routing: ^1.0.0
  flipper_models: any

  google_fonts: ^6.1.0
  shared_preferences: ^2.3.2
  newrelic_mobile: ^1.0.5
  flutter_local_notifications: ^19.0.0-dev.4
 
  window_manager: ^0.4.0
  launcher_entry: ^0.1.1
  internet_connection_checker: ^1.0.0+1
  talker_flutter: ^4.1.5
  supabase_flutter: ^2.8.0
  firebase_core: ^3.8.1
  cbl_flutter_ce: ^3.1.3
  cbl_flutter: ^3.1.3
  supabase_models: any
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.5.0
  package_info_plus: ^8.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.0
  build_runner: ^2.4.14
  test:
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/flipper.pem
