name: flipper_services
description: flipper models scaffold.
version: 0.0.1-dev.6

# publish_to: "none"
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked: ^3.2.5
  firebase_remote_config: ^3.0.2
  share_plus: ^4.0.3
  in_app_review: ^2.0.4
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^12.0.3
  get_storage: ^2.0.3
  # image: ^3.0.2
  image: ^4.0.15
  flipper_routing: ^0.0.1-dev.3
  flipper_models: ^0.0.1-dev.7
  firebase_auth: ^4.6.1-flipper
  # the bellow package has outdated image package, but I do not It is needed now
  # esc_pos_utils_plus: ^2.0.1+3
  nfc_manager: ^3.2.0
  geolocator: ^9.0.2
  geocode: ^1.0.1

  firebase_analytics: ^10.0.2
  firebase_crashlytics: ^3.0.2
  location: 5.0.0-dev.8
  flutter_luban: ^0.1.13
  flutter_uploader: ^3.0.0-beta.4
  injectable: ^1.5.3
  google_sign_in: ^5.0.0
  firebase_dynamic_links: ^5.0.2
  http: ^0.13.6
  intl: ^0.18.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  path: ^1.8.2
  googleapis: ^8.1.0

  timeago: ^3.2.1
  pubnub: ^4.2.2
  stacked_services: ^1.0.0
  universal_platform: ^1.0.0+1
  googleapis_auth: ^1.1.0
  get_it: ^7.2.0
  uuid: ^3.0.5
  url_launcher: ^6.1.2
  flipper_nfc: ^1.2.0
  timezone: ^0.9.1
  flutter_native_timezone: ^2.0.0
  connectivity_plus: ^2.3.9
  flutter_statusbarcolor_ns: ^0.5.0
  pocketbase: ^0.7.2

dev_dependencies:
  build_runner: ^2.0.0
  # objectbox_generator: ^1.4.0
  injectable_generator:
  test:
