name: flipper_services
description: flipper models scaffold.
version: 0.0.1-dev.2

# publish_to: "none"
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper: ^99.99.99+99
  stacked: ^2.2.8
  firebase_remote_config: ^2.0.0
  flutter_secure_storage: ^5.0.2
  share_plus: ^2.1.4
  system_time_check: ^1.0.0
  in_app_review: ^2.0.4
  firebase_messaging: ^11.2.3
  flutter_local_notifications: ^6.0.0
  get_storage: ^2.0.3
  image: ^3.0.2
  flipper_routing: ^0.0.1+1
  flipper_models: ^0.0.1-dev.2
  firebase_auth: ^3.3.5
  esc_pos_utils_plus: ^2.0.1+3
  bluetooth_thermal_printer: ^0.0.6
  geolocator: ^8.0.5
  geocode: ^1.0.1
  cron: ^0.4.0
  dio: ^4.0.4
  extension_google_sign_in_as_googleapis_auth: ^2.0.3
  firebase_analytics: ^8.0.3
  firebase_crashlytics: ^2.5.0
  location: ^4.3.0
  flutter_luban: ^0.1.13
  flutter_uploader: ^3.0.0-beta.3
  injectable: ^1.5.3
  google_sign_in: ^5.2.3
  firebase_dynamic_links: ^4.0.5
  http: ^0.13.4
  intl: ^0.17.0
  image_picker: ^0.8.4+6
  path_provider: ^2.0.8
  flutter_chat_types: ^3.2.0
  path: ^1.8.0
  googleapis: ^5.0.1
  flutter_firebase_chat_core: ^1.5.0
  go_router: ^3.0.1
  timeago: ^3.2.1
  pubnub: ^4.1.0
  stacked_services: ^0.8.16
  universal_platform: ^1.0.0+1
  googleapis_auth: ^1.3.0
  get_it: ^7.2.0
  uuid: ^3.0.5
  cloud_firestore: ^3.1.7
