name: firestore_models
description: "A new Flutter package project."
version: 1.0.0
# homepage:

environment:
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  cloud_firestore_odm: ^1.0.0-dev.88
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  riverpod_lint: ^2.3.7
  dart_mappable_builder: ^4.2.1
  custom_lint: ^0.6.4
  mockito: ^5.4.4
  json_serializable: ^6.8.0 
  cloud_firestore_odm_generator: ^1.0.0-dev.89
  cloud_firestore: ^5.4.3
  flipper_models: any
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.4.7
  stacked_services: ^1.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

