name: flipper_infra
description: "A new Flutter package project."
version: 0.0.1
# homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  time: ^2.1.4
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.5.4