name: flipper_ui
description: >
  A new Flutter package project.
version: 1.0.3
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_loading: ^2.0.0
  overlay_support: ^2.1.0
  # adding this because I need constants from it,
  # maybe it is time to move all constants to its own package
  flipper_services: ^1.0.0-dev
  flutter_window_close: ^0.2.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  fluent_ui: ^4.8.2
dependency_overrides:
  http: ^1.2.1
  meta: ^1.12.0
  sane_uuid: 1.0.0-alpha.5
