name: flipper_ui
description: >
  A new Flutter package project.
version: 0.0.2
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_loading: ^2.0.0
  flutter_screenutil: ^5.1.0
