name: flipper_routing
description: A new Flutter package project.
version: 1.0.0
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flipper_dashboard: any
  flipper_login: any
  flipper_models: any
  stacked_services: ^1.6.0
  stacked: ^3.4.2
  url_strategy: ^0.2.0
  logger: ^1.1.0
  firebase_ui_auth: ^1.16.0
  flipper_actionable: 0.0.1
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^1.0.0
  json_annotation: ^4.9.0
  sqlite3: ^2.5.0
  stacked: ^3.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.5.2
  mockito: ^5.4.4
