name: flipper_routing
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #flipper:
  go_router: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator:
  injectable_generator:
  stacked_generator:
  flutter_lints:
  flipper_chat:
  flipper_dashboard:
  flipper_login:
  flipper_models:
  stacked_services:
  flipper:
  flipper_finance:
  logger:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
