name: flipper_routing
description: A new Flutter package project.
version: 0.0.1-dev.3
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flipper_dashboard: ^0.0.1-dev.5
  flipper_login: ^0.0.1-dev.5
  flipper_models: ^0.0.1-dev.7
  stacked_services: ^1.0.4
  stacked: ^3.4.0
  url_strategy: ^0.2.0
  flipper_finance: ^0.0.1
  logger: ^1.1.0
  firebase_ui_auth: ^1.6.4
  flipper_actionable: 0.0.1
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: 1.0.0
  mockito: ^5.3.2
