name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.7
repository: https://github.com/yegobox/packages


environment:
  sdk: ">=3.0.0"


dependencies:
  equatable: ^2.0.3
  json_serializable: ^6.7.1
  meta: ^1.3.0
  firebase_auth_desktop: ^1.0.2-flipper
  universal_platform: ^1.0.0+1
  stacked_services: ^1.0.4
  firebase_auth: ^4.8.0
  stacked: ^3.4.0
  built_value: ^8.1.4
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.3.2-dev
  uuid: ^3.0.7
  built_collection: ^5.1.1
  flipper_services: ^1.0.0
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^4.0.1
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  pocketbase: ^0.10.0
  stock: ^1.0.1
  sentry_flutter: ^7.9.0
  path_provider: ^2.0.15
  http: ^1.1.0
  html_unescape: ^2.0.0
  json_annotation: ^4.8.1
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.4