name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.7
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0
  firebase_auth_desktop: ^1.0.0
  universal_platform: ^1.0.0+1
  stacked_services: ^0.8.16
  firebase_auth: ^3.3.19
  go_router: ^3.1.0
  stacked: ^2.2.5
  # objectbox: ^1.4.1
  # objectbox_sync_flutter_libs: ^1.4.1
  built_value: ^8.1.4
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.3.2-dev
  flutter_chat_types: ^3.3.0
  uuid: ^3.0.5
  built_collection: ^5.1.1
  flipper_chat: ^0.0.1-dev.5
  flipper_services: ^0.0.1-dev.6
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^2.2.0
  isar: 3.0.1
  isar_flutter_libs: 3.0.1

dev_dependencies:
  build_runner: ^2.1.7
  isar_generator: 3.0.1
  test:
