name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.7
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  equatable: ^2.0.3
  json_serializable: ^6.7.1
  meta: ^1.3.0
  # firebase_auth_desktop: ^1.0.2-flipper
  universal_platform: ^1.0.0+1
  stacked_services: ^1.0.4
  firebase_auth: ^4.12.0
  stacked: ^3.4.1+1
  built_value: ^8.1.4
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.3.2-dev
  uuid: ^3.0.7
  built_collection: ^5.1.1
  flipper_services: ^1.0.0
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^5.0.1
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  pocketbase: ^0.15.1
  stock: ^1.0.1
  sentry_flutter: ^7.9.0
  path_provider: ^2.0.15
  http: ^1.1.0
  html_unescape: ^2.0.0
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks:
  riverpod: ^2.0.0
  hooks_riverpod: ^2.0.0
  freezed_annotation:
  # cloud_firestore: ^4.13.1
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.4
  custom_lint:
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  freezed:
