name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.5
# publish_to: "none"
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta: ^1.3.0
  firebase_auth_desktop: ^0.1.1-dev.0
  flipper_services: ^0.0.1-dev.6
  flipper_routing: ^0.0.1-dev.3
  universal_platform: ^1.0.0+1
  stacked_services: ^0.8.16
  firebase_auth: ^3.3.5
  go_router: ^3.0.1
  stacked: ^2.2.5
  objectbox: ^1.3.0
  objectbox_sync_flutter_libs: ^1.3.0
  built_value: ^8.1.4
  azlistview: ^2.0.0-nullsafety.0
  scrollable_positioned_list: ^0.2.3
  flutter_chat_types: ^3.3.0
  uuid: ^3.0.5
  built_collection: ^5.1.1
  flipper_chat: ^0.0.1-dev.5
  connectivity_plus: ^2.2.0
  isar_flutter_libs: ^2.2.0+1
  isar: ^2.2.0+1
dev_dependencies:
  build_runner: ^2.1.7
  # Enable when buildig objectbox and disable isar generator as they are not playing nice
  objectbox_generator: 1.3.0
  # isar_generator: 2.2.0+1
  json_serializable:
  built_value_generator:
# dependency_overrides:
#   objectbox_generator:
#     path: packages/generator
