name: flipper_models
description: flipper models scaffold.
version: 0.0.1-dev.7
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=3.0.0"

dependencies:
  equatable: ^2.0.3
  json_serializable: ^6.8.0
  meta: ^1.3.0
  universal_platform: ^1.0.0+1
  stacked_services: ^1.0.4
  firebase_auth: ^4.19.6
  stacked: ^3.4.2
  built_value: ^8.1.4
  azlistview: ^2.0.0
  scrollable_positioned_list: ^0.3.2-dev
  built_collection: ^5.1.1
  flipper_services: ^1.0.0-dev
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^6.0.3
  pocketbase: ^0.17.0
  stock: ^1.0.1
  sentry_flutter: ^8.2.0
  path_provider: ^2.1.3
  http: ^1.2.1
  html_unescape: ^2.0.0
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks: ^0.18.0
  riverpod: ^2.0.0
  hooks_riverpod: ^2.0.0
  freezed_annotation: ^2.3.0
  # cloud_firestore: ^4.14.0
  isolated_worker: ^0.1.1
  # adding realm to replace firestore on desktop in transporting data to cloud
  realm: 2.2.1
  uuid: ^4.3.3
  dart_mappable: ^4.2.1
  dio: ^5.4.3+1
  talker_dio_logger: ^4.1.5
  talker: ^4.1.5
  talker_flutter: ^4.1.5
  rxdart: ^0.27.7
  collection: ^1.18.0
  intl: ^0.18.0

dependency_overrides:
  http: ^1.2.1
  meta: ^1.12.0
  analyzer: ^6.0.0

dev_dependencies:
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.7
  dart_mappable_builder: ^4.2.1
  isar_generator: ^3.1.0+1
  custom_lint: ^0.6.4
