name: flipper_finance
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  adaptive_breakpoints: ^0.1.0
  animations: ^2.0.0
  google_fonts: ^4.0.3
