name: flipper_chat
description: A new Flutter package project.
version: 0.0.1-dev.5
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_rw: ^1.0.1-dev.3
  flipper_routing: ^0.0.1-dev.3
  flipper_services: ^0.0.1-dev.6
  flipper_dashboard: ^0.0.1-dev.5
  flutter_chat_types: ^3.3.0
  flutter_chat_ui: ^1.5.5
  flutter_firebase_chat_core: ^1.5.0
  timeago: ^3.2.1

  mime: ^1.0.1
  open_filex: ^4.1.1
  image_picker: ^0.8.0+4
  firebase_storage: ^11.0.2
  file_picker: ^4.6.1-dev
  go_router: ^3.1.0
  stacked: ^3.0.0
  azlistview: ^2.0.0
  flipper_models: ^0.0.1-dev.7
  ionicons: ^0.1.2
  flipper_ui: ^1.0.3
  universal_platform: ^1.0.0+1
  overlay_support: ^2.0.0-beta.0

  firebase_auth: ^4.0.2
  flutter_text_drawable: ^1.0.0
  flutter_slidable: 1.3.0
  http: ^0.13.4
  path_provider: ^2.0.8
  flutter_svg: ^1.1.1+1
  qr: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - ../../assets/logo.png
    - ../../assets/
    - ../../assets/images/
    - ../../assets/icons/
    - ../../google_fonts/

generate: true
