name: flipper_chat
description: A new Flutter package project.
version: 0.0.1
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flipper:
  flipper_routing:
  flipper_services:
  flipper_dashboard:
  flutter_chat_types:
  flutter_chat_ui:
  flutter_firebase_chat_core:
  timeago:
  stacked_themes:
  mime: ^1.0.1
  open_file: ^3.2.1
  image_picker: ^0.8.0+4
  firebase_storage: ^10.2.5
  file_picker: ^4.2.7
  go_router: ^3.0.1
  stacked: ^2.2.8
  azlistview: ^2.0.0-nullsafety.0
