name: flipper_chat
description: A new Flutter package project.
version: 0.0.1-dev.5
repository: https://github.com/yegobox/packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_rw: ^1.0.1-dev.3
  flipper_routing: ^0.0.1-dev.3
  flipper_services: ^0.0.1-dev.6
  flipper_dashboard: ^0.0.1-dev.5
  flutter_chat_types: ^3.3.0
  flutter_chat_ui: ^1.5.5
  flutter_firebase_chat_core: ^1.5.0
  timeago: ^3.2.1
  stacked_themes: ^0.3.8+1
  mime: ^1.0.1
  open_file: ^3.2.1
  image_picker: ^0.8.0+4
  firebase_storage: ^10.2.5
  file_picker: ^4.2.7
  go_router: ^3.0.1
  stacked: ^2.2.8
  azlistview: ^2.0.0-nullsafety.0
  flipper_models: ^0.0.1-dev.5
  ionicons: ^0.1.2
  flipper_ui: ^1.0.3
  universal_platform: ^1.0.0+1
  overlay_support: ^1.2.1

  firebase_auth: ^3.3.5
  flutter_text_drawable: ^1.0.0
  flutter_slidable: ^0.6.0
  http: ^0.13.4
  path_provider: ^2.0.8
  flutter_svg: ^1.0.3
  qr: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - ../../assets/fliper-logo.png
    - ../../assets/
    - ../../assets/images/
    - ../../assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: ../../assets/fonts/Poppins/Poppins-Light.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
        - asset: ../../assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
        - asset: ../../assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
generate: true
