name: flipper_login
description: >
  flipper models scaffold.
version: 0.0.1-dev.5
repository: https://github.com/yegobox/packages

# publish_to: "none"

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_ui_auth: ^1.11.0
  flutter_form_bloc: 0.31.0-dev
    # git:
    #   url: https://github.com/Cavin6080/form_bloc.git
    #   path: packages/flutter_form_bloc
  # firebase_auth_desktop: ^1.0.2-flipper
  firebase_core: ^2.24.2
  # firebase_core_desktop: ^1.0.2-dev
  flipper_services: ^1.0.0
  flipper_dashboard: ^0.0.1-dev.5
  universal_platform: ^1.0.0+1
  flipper_models: ^0.0.1-dev.7
  flutter_carousel_slider: ^1.0.9
  country_code_picker: ^3.0.0
  overlay_support: ^2.1.0
  flutter_settings_ui: ^2.0.1
  stacked: ^3.4.1+1
  google_fonts: ^6.1.0
# Do not update firebase_auth https://github.com/firebase/flutterfire/issues/5964
  firebase_auth: ^4.15.3
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^5.0.2
  firebase_ui_localizations: ^1.9.0
  firebase_ui_oauth: ^1.4.13
  firebase_ui_oauth_google: ^1.2.13
  flutter_svg: ^2.0.0
  gap: ^2.0.0
  qr_flutter: ^4.1.0
  flipper_ui: ^1.0.3
  flipper_socials: 1.0.0+1
  flutter_riverpod: ^2.4.5
  riverpod_annotation: ^2.3.0
  flutter_hooks:
  riverpod: ^2.0.0
  hooks_riverpod: ^2.0.0
dependency_overrides:
  http: ^1.1.2
  meta: ^1.11.0
flutter:
  assets:
    - assets/
    - google_fonts/
