name: flipper_login
description: >
  flipper models scaffold.
version: 0.0.1
repository: https://github.com/yegobox/packages

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper:
  flutterfire_ui: ^0.3.1
  flutter_form_bloc: ^0.29.3
