name: flipper_login
description: >
  flipper models scaffold.
version: 0.0.1-dev.5
repository: https://github.com/yegobox/packages

# publish_to: "none"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flipper_rw: ^1.0.1-dev.3
  flutterfire_ui: ^0.3.5+1
  flutter_form_bloc: ^0.29.3
  firebase_auth_desktop: ^0.1.1-dev.0
  firebase_core: ^1.9.0
  firebase_core_desktop: ^0.1.1-dev.0
  flipper_services: ^0.0.1-dev.6
  flipper_dashboard: ^0.0.1-dev.5
  universal_platform: ^1.0.0+1
  flipper_models: ^0.0.1-dev.5
  overlay_support: ^1.2.1
  flutter_settings_ui: ^2.0.1
  stacked: ^2.2.8
  google_fonts: ^2.1.0
  flipper_ui: ^1.0.3
  firebase_auth: ^3.3.5
  go_router: ^3.0.1
  flipper_routing: ^0.0.1-dev.3
  connectivity_plus: ^2.2.0
  google_ui: ^2.7.0
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  qr_flutter: ^4.0.1
dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_database_platform_interface: 0.2.0+5
  cloud_firestore_web: 2.6.5

flutter:
  uses-material-design: true
  assets:
    - ../../assets/fliper-logo.png
    - ../../assets/
    - ../../assets/images/
    - ../../assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: ../../assets/fonts/Poppins/Poppins-Light.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
        - asset: ../../assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
        - asset: ../../assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: ../../assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
generate: true
