name: flipper_data_table
description: A new Flutter package project.
version: 1.0.0-dev.2

repository: https://github.com/yegobox/packages

sdk: ">=3.0.0"

dependencies:
  flipper_models: ^0.0.1-dev.7
  flutter_riverpod: ^2.3.6
dependency_overrides:
  http: ^1.1.0
  # freezed_annotation: ^0.14.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - ../../google_fonts/
