name: Deploy to Play Store

on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      lane:
        description: "Fastlane lane"
        required: true
        default: "internal"
        type: choice
        options:
          - beta
          - promote_to_production
          - production

  # Refs/tags push events to matching v*, i.e. v1.0, v20.15.10
  push:
    branches: [main, dev]
    # tags:
    # - 'v*'

env:
  URL: ${{ secrets.DB_URL }}
  PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  unit-testing:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
         with:
           submodules: recursive
           token: ${{ secrets.ACCESS_TOKEN }}
           persist-credentials: true

       - uses: actions/setup-java@v2
         with:
           distribution: "zulu"
           java-version: "11"

       - uses: subosito/flutter-action@v2
         with:
           flutter-version: '3.19.3'
           channel: "stable"

       - run: git submodule update --init

       - name: Configure Missing files
         shell: bash
         run: |
           echo "$INDEX" >> apps/main_app/web/index.html
           echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
           echo "$SECRETS" >> packages/flipper_models/lib/secrets.dart
           echo "$FIREBASEOPTIONS" >> apps/main_app/lib/firebase_options.dart
           echo "$FIREBASEOPTIONS" >> packages/flipper_models/lib/firebase_options.dart
           git config --global core.autocrlf false
         env:
           INDEX: ${{ secrets.INDEX }}
           CONFIGDART: ${{ secrets.CONFIGDART }}
           SECRETS: ${{ secrets.SECRETS }}
           FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}

       - run: |
           dart pub global activate melos
           melos bootstrap
           cd apps/main_app
           flutter test --dart-define=Test=true

  integration-testing-windows:
     name: "Integration Testing Windows"
     runs-on: windows-2022
#     needs: [unit-testing]
#     https://github.com/subosito/flutter-action/issues/278 isse of windows failing to build
#   https://github.com/subosito/flutter-action/issues/277#issuecomment-1974628019
     steps:
       - name: Export pub environment variable on Windows
         run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
             echo "PUB_CACHE=$LOCALAPPDATA\\Pub\\Cache" >> $GITHUB_ENV
           fi
         shell: bash
       - run: git config --global core.autocrlf false
       - uses: actions/checkout@v4
         with:
           submodules: recursive
           token: ${{ secrets.ACCESS_TOKEN }}
           persist-credentials: true
       - name: Clone Flutter repository with stable channel
         uses: subosito/flutter-action@v2
         with:
           flutter-version: "3.19.3"
           channel: stable
       - run: flutter doctor -v

       - uses: actions/setup-java@v2
         with:
           distribution: "zulu"
           java-version: "11"

       - name: submodule init
         run: git submodule update --init
       - name: Configure Missing files
         shell: bash
         run: |
           echo "$INDEX" >> apps/main_app/web/index.html
           echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
           echo "$SECRETS" >> packages/flipper_models/lib/secrets.dart
           echo "$FIREBASEOPTIONS" >> apps/main_app/lib/firebase_options.dart
           echo "$FIREBASEOPTIONS" >> packages/flipper_models/lib/firebase_options.dart
         env:
           INDEX: ${{ secrets.INDEX }}
           CONFIGDART: ${{ secrets.CONFIGDART }}
           SECRETS: ${{ secrets.SECRETS }}
           FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
       - run: |
           dart pub global activate melos
           melos bootstrap
           cd apps/main_app
           flutter test --dart-define=Test=true -d windows integration_test/smoke_windows_test.dart

  build-and-release-windows:
      name: "Build windows app"
      runs-on: windows-2022
      #     needs: [unit-testing]
      #     https://github.com/subosito/flutter-action/issues/278 isse of windows failing to build
      #   https://github.com/subosito/flutter-action/issues/277#issuecomment-1974628019
      steps:
        - name: Export pub environment variable on Windows
          run: |
            if [ "$RUNNER_OS" == "Windows" ]; then
              echo "PUB_CACHE=$LOCALAPPDATA\\Pub\\Cache" >> $GITHUB_ENV
            fi
          shell: bash
        - run: git config --global core.autocrlf false
        - uses: actions/checkout@v4
          with:
            submodules: recursive
            token: ${{ secrets.ACCESS_TOKEN }}
            persist-credentials: true
        - name: Clone Flutter repository with stable channel
          uses: subosito/flutter-action@v2
          with:
            flutter-version: "3.19.3"
            channel: stable
        - run: flutter doctor -v

        - uses: actions/setup-java@v2
          with:
            distribution: "zulu"
            java-version: "11"

        - name: submodule init
          run: git submodule update --init
        - name: Configure Missing files
          shell: bash
          run: |
            echo "$INDEX" >> apps/main_app/web/index.html
            echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
            echo "$SECRETS" >> packages/flipper_models/lib/secrets.dart
            echo "$FIREBASEOPTIONS" >> apps/main_app/lib/firebase_options.dart
            echo "$FIREBASEOPTIONS" >> packages/flipper_models/lib/firebase_options.dart
          env:
            INDEX: ${{ secrets.INDEX }}
            CONFIGDART: ${{ secrets.CONFIGDART }}
            SECRETS: ${{ secrets.SECRETS }}
            FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
        - run: |
            dart pub global activate melos
            melos bootstrap
            cd apps/main_app
            dart run msix:create --store 
        - name: Configure Release (optional)
          env:
            VERSION: ${{ github.sha }}  # Or use a semantic versioning scheme
          run: |
            echo "## Release Notes" >> release_notes.txt
            echo " - New features..." >> release_notes.txt
            echo " - Bug fixes..." >> release_notes.txt
        - name: Set VERSION environment variable
          shell: bash
          run: |
            VERSION=$(grep 'msix_version:' pubspec.yaml | cut -d: -f2 | tr -d '[:space:]')
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Create Release
          uses: actions/create-release@v1
          with:
            tag_name: ${{ env.VERSION }}
            release_name: Windows Release ${{ env.VERSION }}
#            body_path: release_notes.txt  # Optional: Path to release notes file https://github.com/actions/create-release
            draft: false  # Set to true for draft releases
            prerelease: false
            body: |
              Changes in this Release
              - First Change
              - Second Change
          env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              VERSION: |
                $(grep 'msix_version:' pubspec.yaml | cut -d: -f2 | tr -d '[:space:]')
        
        

        - name: Upload Build Artifact (optional)
          uses: actions/upload-artifact@v3
          with:
            name: windows-build
            path: build/windows/x64

  # android-integration-test:
  #   name: run integration test on Android emulator
  #   runs-on: macOS-latest
  #   strategy:
  #     matrix:
  #       api-level: [33]
  #       target: [playstore]
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         distribution: "zulu"
  #         java-version: "11"
  #     - name: Clone Flutter repository with stable channel
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.19.3"
  #         channel: stable
  #     - name: Configure Git with PAT
  #       env:
  #         PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  #       run: |
  #         git config --global user.email "info@yegobox.com"
  #         git config --global user.name "YEGOBOX"
  #         git config --global credential.helper store
  #         echo "https://github.com:${PAT_TOKEN}@github.com" > ~/.git-credentials
  #     - name: submodule init
  #       run: git submodule update --init
  #     - name: Configure Missing files
  #       run: |
  #         echo "$INDEX" >> apps/main_app/web/index.html
  #         echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
  #         echo "$SECRETS" >> packages/flipper_models/lib/secrets.dart
  #         echo "$FIREBASEOPTIONS" >> apps/main_app/lib/firebase_options.dart
  #         echo "$FIREBASEOPTIONS" >> packages/flipper_models/lib/firebase_options.dart
  #         git config --global core.autocrlf false
  #       env:
  #         INDEX: ${{ secrets.INDEX }}
  #         CONFIGDART: ${{ secrets.CONFIGDART }}
  #         SECRETS: ${{ secrets.SECRETS }}
  #         FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
  #     - name: Configure Keystore
  #       run: |
  #         echo "$GOOGLE_SERVICE_JSON" > app/google-services.json
  #         echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/key.jks
  #         echo "storeFile=key.jks" >> key.properties
  #         echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
  #         echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
  #         echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
  #       env:
  #         PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
  #         KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  #         KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  #         KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  #         GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
  #       working-directory: android
  #     - run: |
  #         dart pub global activate melos
  #         melos bootstrap
  #     - name: Install Android SDK
  #       uses: malinskiy/action-android/install-sdk@release/0.1.2
  #     - run: echo $ANDROID_HOME
  #     - run: sdkmanager --install "ndk;23.1.7779620"
  #     - run: sdkmanager --install "build-tools;30.0.3"
  #     - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
  #       with:
  #         cmd: flutter test --dart-define=Test=true  integration_test/smoke_android_test.dart
  #         api: 33
  #         cmdOptions: -no-snapshot-save -noaudio -no-boot-anim -cores 2 -memory 3072 -no-window
  #         tag: google_apis
  #         abi: x86_64
      # ----------------------------------------------------------
      # TODO: the bellow code should not be uncommented accidently
      # - name: Run Flutter Driver tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     target: ${{ matrix.target }}
      #     api-level: ${{ matrix.api-level }}
      #     arch: x86_64
      #     profile: Nexus 6
      #     force-avd-creation: true
      #     ram-size: 4096M
      #     heap-size: 512M   
      #     avd-name: macOS-avd-arm64-v8a-31
      #     emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: true
      #     script: flutter test --dart-define=Test=true  integration_test/smoke_android_test.dart
      #     emulator-boot-timeout: 1800
       # Update screenshot to artifact
      # - name: Upload screenshots
      #   if: always()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: screenshot
      #     path: ${{ matrix.path }}screenshots/

  fastlane-deploy:
    name: "Google Deploy"
    needs: [unit-testing,integration-testing-windows]
    runs-on: ubuntu-22.04
    steps:
      - run: git config --global core.autocrlf false
      # Set up Flutter.
      - name: Clone Flutter repository with stable channel
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3" #firebase_auth_desktop is broken with  3.10.6
          channel: stable
      - run: flutter doctor -v

      # Checkout flipper code
      - name: Checkout flipper code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-java@v2 #plugin for setting up the java
        with:
          distribution: "zulu"
          java-version: "11" #defines the java version
      - name: Configure Git with PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "info@yegobox.com"
          git config --global user.name "YEGOBOX"
          git config --global credential.helper store
          echo "https://github.com:${PAT_TOKEN}@github.com" > ~/.git-credentials
      - name: submodule init
        run: git submodule update --init
      - name: Configure Missing files
        run: |
          echo "$INDEX" >> apps/main_app/web/index.html
          echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
          echo "$SECRETS" >> packages/flipper_models/lib/secrets.dart
          echo "$FIREBASEOPTIONS" >> apps/main_app/lib/firebase_options.dart
          echo "$FIREBASEOPTIONS" >> packages/flipper_models/lib/firebase_options.dart
          git config --global core.autocrlf false
        env:
          INDEX: ${{ secrets.INDEX }}
          CONFIGDART: ${{ secrets.CONFIGDART }}
          SECRETS: ${{ secrets.SECRETS }}
          FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
      - run: |
          dart pub global activate melos
          melos bootstrap
      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          # cache-version: 1
          working-directory: apps/main_app/android
      - name: Configure Keystore
        run: |
          echo "$GOOGLE_SERVICE_JSON" > app/google-services.json
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/key.jks
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode  > play_store_upload_key.txt
          cat play_store_upload_key.txt
          echo "storeFile=key.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE_JSON }}
        working-directory: apps/main_app/android

      # Build and deploy with Fastlane (by default, to beta track) ðŸš€.
      # Naturally, promote_to_production only deploys.
      # https://stackoverflow.com/questions/22301956/error-with-gradlew-usr-bin-env-bash-no-such-file-or-directory
      - run: |
          bundle exec fastlane ${{ github.event.inputs.lane || 'internal' }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        working-directory: apps/main_app/android

  slackNotification:
    name: Slack Notification
    needs: [fastlane-deploy]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
