name: flipper_actionable
description: A new Flutter package project.
version: 0.0.1


environment:
  flutter: ^3.19.3
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  injectable: ^2.4.0
  get_it: ^7.6.0
  stacked: ^3.4.1+1
  flipper_services: ^1.0.0-dev
  meta: ^1.12.0
dependency_overrides:
  http: ^1.2.1
  meta: ^1.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.6.0
  build_runner: ^2.4.8
