name: flipper_actionable
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=3.0.0"

dependencies:
  intl: ^0.18.0
  injectable: ^2.3.0
  
  get_it: ^7.6.0
  stacked: ^3.4.1+1
  flipper_services: ^1.0.0-dev
  meta: ^1.11.0
dependency_overrides:
  http: ^1.1.2
  meta: ^1.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.0
  build_runner: ^2.4.4
